// import type { Metadata } from 'next';
'use client'
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeContextProvider } from './Context/ThemeContext';
import { ChatContextProvider } from './Context/ChatContext';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ThemeContextProvider>
          <ChatContextProvider>
            <>
              {children}
            </>
          </ChatContextProvider>
        </ThemeContextProvider>

      </body>
    </html>
  );
}
